pull_request_rules:
- name: Automatic merge on approval
  actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - -files~=^noggin/security/
  - label!=WIP
  - approved-reviews-by=@fedora-infra/authdev
  - "#approved-reviews-by>=1"
  - status-success=DCO
  - status-success=CI on f32
  - status-success=CI on f33

- name: Sensitive files
  actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - files~=^noggin/security/
  - label!=WIP
  - approved-reviews-by=@fedora-infra/authdev
  - "#approved-reviews-by>=2"
  - status-success=DCO
  - status-success=CI on f32
  - status-success=CI on f33
